sudo: false

language: node_js

node_js:
  - 7
  - 6

cache: yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

install:
  - export CXX="g++-4.8"
  - npm install -g yarn@latest
  - yarn
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - yarn test-all
  - yarn package

osx_image: xcode8.3
